<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pos.Data\Pos.Data.csproj" />
    <ProjectReference Include="..\..\src\Pos.Localization\Pos.Localization.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Users\Pos.Modules.Users.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Products\Pos.Modules.Products.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.CashRegister\Pos.Modules.CashRegister.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Sales\Pos.Modules.Sales.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Inventory\Pos.Modules.Inventory.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Invoicing\Pos.Modules.Invoicing.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Printing\Pos.Modules.Printing.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Hardware\Pos.Modules.Hardware.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Bazaar\Pos.Modules.Bazaar.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.DataTransfer\Pos.Modules.DataTransfer.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pos.Modules.Verifactu\Pos.Modules.Verifactu.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\locales\*.json" Link="locales\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
